//defines.h

#define READBIT(WORD,BITPOS) ((WORD>>BITPOS)&1)
#define WRITEBIT(WORD,BITPOS,VALUE) WORD=((WORD&~(1<<BITPOS))|(VALUE<<BITPOS))
#define READNIBBLE(WORD,NIBBLESTARTBITPOS) \
				((WORD>>NIBBLESTARTBITPOS)&0X0F)
#define WRITENIBBLE(WORD,NIBBLESTARTBITPOS,VALUE) \
				WORD=((WORD&~(0X0F<<NIBBLESTARTBITPOS)) | (VALUE<<NIBBLESTARTBITPOS))
#define READBYTE(WORD,BYTESTARTBITPOS) \
				((WORD>>BYTESTARTBITPOS)&0XFF)
#define WRITEBYTE(WORD,BYTESTARTBITPOS,VALUE) \
				WORD=((WORD&~(0XFF<<BYTESTARTBITPOS))|(VALUE<<BYTESTARTBITPOS))
#define READWRITEBIT(WORD,BITPOS,VALUE)\
				(((WORD>>BITPOS)&1) | (WORD&~(1<<BITPOS))|(VALUE<<BITPOS))
#define SETBIT(NUM,BITPOS) (NUM|=(1<<BITPOS))
#define CLEARBIT(NUM,BITPOS) (NUM&=~(1<<BITPOS))
#define TOGGLEBIT(NUM,BITPOS) (NUM^=(1<<BITPOS))
